### ISSUE TITLE
Styling für Schlagwort-Wolke wie andere Widgets auch auf Hintergrund

### ISSUE THREAD

**Issue by modulbuero** [kre8tiv/urwahl3000#32]
Links ursprünglicher Style, rechts angepasst:
![grafik](https://user-images.githubusercontent.com/12082331/48198079-f8c32a80-e357-11e8-922a-a4a4db3fc371.png) ![grafik](https://user-images.githubusercontent.com/12082331/48198096-04165600-e358-11e8-97eb-f356700351c2.png)

```css
/* MINI (Mobile etc.) */
@media screen {
	
.widget_tag_cloud a, #footer .widget_tag_cloud a {
	display: inline;
    padding: 0 3px;
    background: transparent;
    color: #afdca7;
    border-radius: 0.3em;
	border-width: 1px;
	border-color: transparent;
	border-style: solid;
}

.widget_tag_cloud a:hover, #footer .widget_tag_cloud a:hover {
    background: transparent;
	color: #ffe000;
	border-color: #afdca7
}

}

/* DESKTOP */
@media only screen and (min-width: 770px) {

.widget_tag_cloud {
    background: #e6e6e6;
    padding: 1.5em;
}

.widget_tag_cloud h3.widgettitle {
    color: #0a321e;
	text-shadow: unset;
}

.widget_tag_cloud a, #footer .widget_tag_cloud a {
	display: inline;
    padding: 0 3px;
    background: transparent;
    color: #46962b;
    border-radius: 0.3em;
	border-width: 1px;
	border-color: transparent;
	border-style: solid;
}

#wrap .widget_tag_cloud a {
    background: transparent;
    color: #46962b;
}	

.widget_tag_cloud a:hover, #footer .widget_tag_cloud a:hover {
	color: #0a321e;
	border-color: #0a321e
}
#wrap .widget_tag_cloud a:hover {
    background: transparent;
}

}
```

_Originally posted by @Harry-von-Borstel in https://github.com/kre8tiv/urwahl3000/issues/30#issuecomment-436977584_
